# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/python:2.7

    steps:
      - checkout

      - run: git submodule sync

      - run: git submodule update --init

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - restore_cache:
          key: site-{{ .Branch }}-webmention_cache-

      - run:
          name: Load environment variables
          command: |
            eval "$(openssl aes-256-cbc -k "${ENCRYPTION_KEY}" -d -in environment.env.enc)"
      - run:
          name: Setup Python environment
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ./venv

      - save_cache:
          key: site-{{ .Branch }}-webmention_cache-{{ checksum ".webmention_cache.json" }}
          paths:
            - .webmention_cache.json

      - run:
          name: Build
          command: |
            . venv/bin/activate
            python build.py

