# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/python:2.7

    steps:
      - restore_cache:
          key: git-{{ .Branch }}

      - checkout

      - run:
          name: Update git submodules
          command: |
            git submodule sync
            git submodule update --init

      - save_cache:
          key: git-{{ .Branch }}
          paths:
            - .git

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - restore_cache:
          key: site-{{ .Branch }}-webmention_cache-

      - run:
          name: Setup and update Python environment
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ./venv

      - run:
          name: Build
          command: |
            eval "\$(openssl aes-256-cbc -k '${ENCRYPTION_KEY}' -d -in environment.env.enc |grep -vE '(^#|^\s*$)')"
            env | grep SECRET | awk 'BEGIN{FS="="}{print $1}'
            . venv/bin/activate
            python build.py

      - save_cache:
          key: site-{{ .Branch }}-webmention_cache-{{ checksum ".webmention_cache.json" }}
          paths:
            - .webmention_cache.json


