name: Build site with Zola

on:
  push:
    #paths-ignore:  
    branches:
      - public-zola

concurrency:
  group: site-build-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Zola environment
        uses: taiki-e/install-action@v2
        with:
          tool: zola

      - name: Build site tools
        run: cd tools/deploy_aws_s3 && cargo build --verbose

      - name: Tar site tools
        run: tar -C tools/deploy_aws_s3/target/debug -cvf deploy_aws_s3.tar deploy_aws_s3

      - name: Save tools artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy_aws_s3
          path: deploy_aws_s3.tar

      - name: Build site
        run: make build

      - name: Save website artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-${{ github.ref_name }}
          path: public/

  call-deploy-workflow:
    uses: ./.github/workflows/deploy.yml
    needs: build
    with:
      artifact-name: website-${{ github.ref_name }}
    secrets:
      AWS_IAM_ROLE_GITHUB: ${{ secrets.AWS_IAM_ROLE_GITHUB }}
